apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: user1
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: 4Gi
    limits.memory: 8Gi
    pods: "20"
