apiVersion: v1
kind: Namespace
metadata:
  name: user1
  labels:
    tenant: user1
---
apiVersion: v1
kind: Namespace
metadata:
  name: user2
  labels:
    tenant: user2
---
apiVersion: v1
kind: Namespace
metadata:
  name: user3
  labels:
    tenant: user3
